### ISSUE TITLE
Autor się objia

### ISSUE THREAD

**Issue by krzysztof-grzybek** [ziunio/threejs-game#1]
Autor się obija, nie rozwija repozytorium. Powinien się uczyć three.js ale jak widać idzie to opornie. Możliwym rozwiązaniem tego problemu jest spotkanie z kolegą ze starej pracy i spożycie napoju alkoholowego w celu pozyskania inspiracji do dalszego działania.

**Comment by ziunio** [comment]
Autor troche zmienil podejscie do tematu zaczal ogarniac silnik oparty na threejs na innym repo :D ale na piwo nalezy isc :D
